#!/bin/bash

function update () {
  zip -r ../be.zip *
  aws lambda update-function-code --function-name bookevents --zip-file fileb://../be.zip
}

echo "Are you sure you want to update production bookevents function?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) update; break;;
        No ) exit;;
    esac
done

